spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amazon-books
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

# Configurações do Swagger/OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs